config:
  project_repos:
    myrepo:
      repo: 'https://github.com/EOSC-synergy/DSpace.git'
      branch: main

environment:
  GIT_COMMITTER_NAME: Fernando
  GIT_COMMITTER_EMAIL: aguilarf@ifca.unican.es
  LANG: C.UTF-8

timeout: 600
